### ISSUE TITLE
Verify Sources Before Clean on Gotham

### ISSUE THREAD

**Issue by craigrs84** [robweber/xbmclibraryautoupdate#29]
"Verify Sources Before Clean - Frodo only! This feature is no longer needed with XBMC Gotham."

It looks like you removed this feature from Gotham because it is no longer needed?  I'm running Gotham and having issues - when the auto updater plugin runs it performs a clean even though my media server is asleep, and the client's library is wiped out.  Any ideas how to fix?  Thanks.

**Comment by robweber** [comment]
Killing this since Gotham is several years old at this point.
