### ISSUE TITLE
Disable dialog when running a manual update?

### ISSUE THREAD

**Issue by leetwanker** [robweber/xbmclibraryautoupdate#33]
I managed to find a place in one of the scripts to change something to 'True' and it would skip the dialog that asks if I want to run a manual update. I run them pretty frequently and if I'm clicking on the updater that is of course what I want it to do. 

I suppose the addon got updated recently and my changes were overwritten. I can't figure out how to do it again. Any advice?

**Comment by robweber** [comment]
I could write a setting for this in the addon settings. I remember this being added as people where having the opposite problem. They were accidentally clicking on the addon or something like that and didn't like the fact it just launched the scan with no dialog. I can see your reasoning to skipping it though. I'll add some kind of "disable dialog on manual run" setting and push it to the repo ASAP. It's a pretty basic fix, I can probably do it today.
