### ISSUE TITLE
Update all in English

### ISSUE THREAD

**Issue by bubuleur** [robweber/xbmclibraryautoupdate#36]
Hello,
I use your addon quite often but since the recent update I do not have it anymore in french
It's normal
Thanking you

**Comment by robweber** [comment]
What version are you on? 1.0.1 should be the one just accepted to the Kodi repo. This update moved everything from the old strings.xml file format to the new strings.po format.  I had thought this was all working but I re-read the language support page and noticed the following: __These folders use "language-country" naming scheme.__ I had used the exact naming from the Transifex site, but apparently every language needs to be named this way. If you rename the resources.language.fr folder to resources.language.fr_fr you'll see the right strings again. I'll have to dig up the right codes for all the other languages and have the addon updated again. Thanks for finding this.

**Comment by bubuleur** [comment]
Thank you for finding the solution
Have a good day
cordially
