### ISSUE TITLE
Library cleaning progress window showed even "Show Notifications" is off

### ISSUE THREAD

**Issue by simonbcn** [robweber/xbmclibraryautoupdate#46]
If I set "_Show Notifications_" to off and I set "_Library cleanup_" to "_After Update_", it shouldn't show the cleaning progress window. It is very annoying and interferes with the application.
Regardless of whether or not it's playing something.

**Comment by robweber** [comment]
In this case I think what you're seeing is not something this addon can control. The "show notifications" toggle has to do with notifications sent by this addon specifically. When you do a clean library call Kodi takes over and puts the cleaning progress window overlay on the screen. Depending on this skin this can look different. I use "Grid" and I know it basically takes over the screen when it happens.
