### ISSUE TITLE
Submit to repo-script matrix branch?

### ISSUE THREAD

**Issue by phunkyfish** [robweber/xbmclibraryautoupdate#54]
Hey Rob,

Firstly, thanks for the addon, it's well used in my house ;)

Can I ask when when you plan to submit it to the repo-scripts matrix (py3) branch?

**Comment by robweber** [comment]
Thanks - glad you're getting use out of it!

Have you tried the matrix nightlies and it's not there? The version in the Leia branch is both python 2 and 3 compatible so I guess I was hoping it would just translate to Matrix. Normally as long as the addon is compatible it will work with version forward of Kodi. If this isn't the case let me know and I'll do a separate PR for Matrix. I haven't tried a nightly in a while, just when I was working on the Python 3 compatibility, the repo wasn't ready yet at that time.

**Comment by phunkyfish** [comment]
Ya, it needs to be submitted separately to the matrix branch. 

I believe it’s Leia and below and then Matrix and above is the cutoff.

Thanks!

**Comment by robweber** [comment]
Good to know. I thought the whole point of making the addons both python 2 and 3 compatible was that they'd filter up if they work on Leia. 

I'll get this done ASAP. It's basically ready so just need to get a PR going. Thanks for pointing this out.

**Comment by phunkyfish** [comment]
Any luck with that PR?

Would like to soak test some Matrix stuff, will start that once this PR is in 😉

**Comment by robweber** [comment]
Sorry, our area went nuts due to COVID-19 so been busy with that. Canceled schools, stuff like that which affected the day to day. 

I'll get to it either tonight or tomorrow though. Starting to find a rhythm again.

**Comment by phunkyfish** [comment]
Don’t worry about it. I completely understand. It’s a trying time for everyone.

**Comment by robweber** [comment]
Got a nightly of Matrix running on a demo PC. I'm running through a few addon update cycles to make sure all dependencies and things work as expected. If there aren't any issues I'll get PR going yet today.

**Comment by phunkyfish** [comment]
Amazing, thanks!

**Comment by robweber** [comment]
Merged - https://github.com/xbmc/repo-scripts/pull/1358

**Comment by phunkyfish** [comment]
Thanks so much!
