### ISSUE TITLE
Not Working with Kodi 20.0

### ISSUE THREAD

**Issue by ThePapaw** [robweber/xbmclibraryautoupdate#73]
I can't get it to work in Kodi 20.0 on android or Windows. "Edit Custom Paths" throwing error as well

**Comment by robweber** [comment]
I'll have to see a debug log. I'm running 20.0 on both my home and dev system and not had any issues. Just tested again now with Custom Paths and no errors here.

**Comment by robweber** [comment]
Closing this as no more information was given.
